/*
* ============================================================================
*  Name     : CGraphDrawView from GraphDrawView.h
*  Part of  : GraphDraw
*  Created  : 3/7/2003 by Makidis Michael
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Copyright: Makidis Michael 2003-2004
* ============================================================================
*/

// INCLUDE FILES
#include  "GraphDrawView.h"
#include  "GraphDrawContainer.h"
#include  <GraphDraw.rsg>
#include  <aknviewappui.h>
#include  <avkon.hrh>

// ================= MEMBER FUNCTIONS =======================

CGraphDrawView::CGraphDrawView(CGraphDrawDocument *aDocument)
:	iDocument(aDocument)
{

}

// ---------------------------------------------------------
// CGraphDrawView::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
void CGraphDrawView::ConstructL()
    {
    BaseConstructL( R_GRAPHDRAW_VIEW1 );
    }

// ---------------------------------------------------------
// CGraphDrawView::~CGraphDrawView()
// ?implementation_description
// ---------------------------------------------------------
//
CGraphDrawView::~CGraphDrawView()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
    }

// ---------------------------------------------------------
// TUid CGraphDrawView::Id()
// ?implementation_description
// ---------------------------------------------------------
//
TUid CGraphDrawView::Id() const
    {
    return KViewId;
    }

// ---------------------------------------------------------
// CGraphDrawView::HandleCommandL(TInt aCommand)
// ?implementation_description
// ---------------------------------------------------------
//
void CGraphDrawView::HandleCommandL(TInt aCommand)
    {
    switch ( aCommand )
        {
		case EGraphDrawDeleteF:
            {
			iDocument->ClearFunction(0);
            break;
            }
		case EGraphDrawDeleteG:
            {
			iDocument->ClearFunction(1);
            break;
            }
		case EGraphDrawDeleteH:
            {
			iDocument->ClearFunction(2);
            break;
            }
		case EGraphDrawDeleteT:
            {
			iDocument->ClearFunction(3);
            break;
            }
		case EGraphDrawZoomIn:
			{
				if(iDocument->iZoom + 500 < 10000000)
					iDocument->iZoom += 500;
				break;
			}
		case EGraphDrawZoomOut:
			{
				if(iDocument->iZoom - 500 > 0)
					iDocument->iZoom -= 500;
				break;
			}
		case EGraphDrawZoomRestore:
			{
				iDocument->iZoom = 1000;
				break;
			}
		case EGraphDrawMoveCenterUp:
			{
				iDocument->iCenter.iY += 10;
				break;
			}
		case EGraphDrawMoveCenterDown:
			{
				iDocument->iCenter.iY -= 10;
				break;
			}
		case EGraphDrawMoveCenterRight:
			{
				iDocument->iCenter.iX += 10;
				break;
			}
		case EGraphDrawMoveCenterLeft:
			{
				iDocument->iCenter.iX -= 10;
				break;
			}
		case EGraphDrawMoveCenterRestore:
			{
				iDocument->iCenterSet = EFalse;
				break;
			}
		case EGraphDrawMoveJoystick:
			{
				iContainer->iMoving = !iContainer->iMoving;
				iContainer->iZooming = EFalse;
				break;
			}
		case EGraphDrawZoomJoystick:
			{
				iContainer->iZooming = !iContainer->iZooming;
				iContainer->iMoving = EFalse;
				break;
			}
        default:
            {
            AppUi()->HandleCommandL( aCommand );
            break;
            }
        }
    }

// ---------------------------------------------------------
// CGraphDrawView::HandleClientRectChange()
// ---------------------------------------------------------
//
void CGraphDrawView::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CGraphDrawView::DoActivateL(...)
// ?implementation_description
// ---------------------------------------------------------
//
void CGraphDrawView::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CGraphDrawContainer(iDocument, this);
        iContainer->SetMopParent(this);
        iContainer->ConstructL( ClientRect() );
        AppUi()->AddToStackL( *this, iContainer );
        } 
   }

// ---------------------------------------------------------
// CGraphDrawView::HandleCommandL(TInt aCommand)
// ?implementation_description
// ---------------------------------------------------------
//
void CGraphDrawView::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

// End of File

