/*
* ============================================================================
*  Name     : CGraphDrawContainer2 from GraphDrawContainer2.cpp
*  Part of  : GraphDraw
*  Created  : 3/7/2003 by Makidis Michael
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Copyright: Makidis Michael 2003-2004
* ============================================================================
*/

// INCLUDE FILES
#include "GraphDrawContainer2.h"
#include "graphdraw.hrh"

// ================= MEMBER FUNCTIONS =======================

CGraphDrawContainer2::CGraphDrawContainer2(CGraphDrawDocument *aDocument)
:	iDocument(aDocument)
{

}

// ---------------------------------------------------------
// CGraphDrawContainer2::ConstructL(const TRect& aRect)
// EPOC two phased constructor
// ---------------------------------------------------------
//
void CGraphDrawContainer2::ConstructL(const TRect& aRect, CGraphDrawView2* aView)
    {
	iView = aView;
    CreateWindowL();

    SetRect(aRect);
    ActivateL();
    }

// Destructor
CGraphDrawContainer2::~CGraphDrawContainer2()
    {
    }

// ---------------------------------------------------------
// CGraphDrawContainer2::SizeChanged()
// Called by framework when the view size is changed
// ---------------------------------------------------------
//
void CGraphDrawContainer2::SizeChanged()
    {
    // TODO: Add here control resize code etc.
    }

// ---------------------------------------------------------
// CGraphDrawContainer2::CountComponentControls() const
// ---------------------------------------------------------
//
TInt CGraphDrawContainer2::CountComponentControls() const
    {
    return 0; // return nbr of controls inside this container
    }

// ---------------------------------------------------------
// CGraphDrawContainer2::ComponentControl(TInt aIndex) const
// ---------------------------------------------------------
//
CCoeControl* CGraphDrawContainer2::ComponentControl(TInt /*aIndex*/) const
    {
	return NULL; // there are NO controls here
    }

// ---------------------------------------------------------
// CGraphDrawContainer2::Draw(const TRect& aRect) const
// ---------------------------------------------------------
//
void CGraphDrawContainer2::Draw(const TRect& /*aRect*/) const
    {
    // nothing to draw
    }

// ---------------------------------------------------------
// CGraphDrawContainer2::HandleControlEventL(
//     CCoeControl* aControl,TCoeEvent aEventType)
// ---------------------------------------------------------
//
void CGraphDrawContainer2::HandleControlEventL(
    CCoeControl* /*aControl*/,TCoeEvent /*aEventType*/)
    {
    // No need to add any control event handler code here
    }

// End of File  
