/*
* ============================================================================
*  Name     : CGraphDrawAppUi from GraphDrawAppUi.cpp
*  Part of  : GraphDraw
*  Created  : 3/7/2003 by Makidis Michael
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Copyright: Makidis Michael 2003-2004
* ============================================================================
*/

// INCLUDE FILES
#include "GraphDrawAppUi.h"
#include "GraphDrawView.h"
#include "GraphDrawView2.h"
#include "GraphDrawView3.h"
#include "graphdraw.hrh"
#include <GraphDraw.rsg>

#include <avkon.hrh>

// ================= MEMBER FUNCTIONS =======================

CGraphDrawAppUi::CGraphDrawAppUi(CGraphDrawDocument *aDocument)
:	iDocument(aDocument)
{

}

//
// ----------------------------------------------------------
// CGraphDrawAppUi::ConstructL()
// ?implementation_description
// ----------------------------------------------------------
//
void CGraphDrawAppUi::ConstructL()
    {
    BaseConstructL( 
#ifdef SERIES_60_V2
		EAknEnableSkin
#endif
		);

    // Show tabs for main views from resources
    CEikStatusPane* sp = StatusPane();

    // Fetch pointer to the default navi pane control
    iNaviPane = (CAknNavigationControlContainer*)sp->ControlL( 
        TUid::Uid(EEikStatusPaneUidNavi));

    // Tabgroup has been read from resource and it were pushed to the navi pane. 
    // Get pointer to the navigation decorator with the ResourceDecorator() function. 
    // Application owns the decorator and it has responsibility to delete the object.
    iDecoratedTabGroup = iNaviPane->ResourceDecorator();
    if (iDecoratedTabGroup)
        {
        iTabGroup = (CAknTabGroup*) iDecoratedTabGroup->DecoratedControl();
        }

    CGraphDrawView* view1 = new (ELeave) CGraphDrawView(iDocument);

    CleanupStack::PushL( view1 );
    view1->ConstructL();
    AddViewL( view1 );      // transfer ownership to CAknViewAppUi
    CleanupStack::Pop();    // view1

    iView2 = new (ELeave) CGraphDrawView2(iDocument);

    CleanupStack::PushL( iView2 );
    iView2->ConstructL();
    AddViewL( iView2 );      // transfer ownership to CAknViewAppUi
    CleanupStack::Pop();    // view2

	CGraphDrawView3* view3 = new (ELeave) CGraphDrawView3(iDocument);

    CleanupStack::PushL( view3 );
    view3->ConstructL();
    AddViewL( view3 );      // transfer ownership to CAknViewAppUi
    CleanupStack::Pop();    // view3

    SetDefaultViewL(*view1);

    }

// ----------------------------------------------------
// CGraphDrawAppUi::~CGraphDrawAppUi()
// Destructor
// Frees reserved resources
// ----------------------------------------------------
//
CGraphDrawAppUi::~CGraphDrawAppUi()
    {
    delete iDecoratedTabGroup;
   }

// ------------------------------------------------------------------------------
// CGraphDrawAppUi::::DynInitMenuPaneL(TInt aResourceId,CEikMenuPane* aMenuPane)
//  This function is called by the EIKON framework just before it displays
//  a menu pane. Its default implementation is empty, and by overriding it,
//  the application can set the state of menu items dynamically according
//  to the state of application data.
// ------------------------------------------------------------------------------
//
void CGraphDrawAppUi::DynInitMenuPaneL(
    TInt /*aResourceId*/,CEikMenuPane* /*aMenuPane*/)
    {
    }

// ----------------------------------------------------
// CGraphDrawAppUi::HandleKeyEventL(
//     const TKeyEvent& aKeyEvent,TEventCode /*aType*/)
// ?implementation_description
// ----------------------------------------------------
//
TKeyResponse CGraphDrawAppUi::HandleKeyEventL(
    const TKeyEvent& aKeyEvent,TEventCode /*aType*/)
    {
    if ( iTabGroup == NULL )
        {
        return EKeyWasNotConsumed;
        }

    TInt active = iTabGroup->ActiveTabIndex();
    TInt count = iTabGroup->TabCount();

    switch ( aKeyEvent.iCode )
        {
        case EKeyLeftArrow:
			// activate the previous tab
            if ( active > 0 )
                {
                active--;
                iTabGroup->SetActiveTabByIndex( active );
                ActivateLocalViewL(TUid::Uid(iTabGroup->TabIdFromIndex(active)));
                }
            break;
        case EKeyRightArrow:
			// activate the next tab
            if( (active + 1) < count )
                {
                active++;
                iTabGroup->SetActiveTabByIndex( active );
                ActivateLocalViewL(TUid::Uid(iTabGroup->TabIdFromIndex(active)));
                }
            break;
        default:
            return EKeyWasNotConsumed;
            break;
        }

    return EKeyWasConsumed;
    }

// ----------------------------------------------------
// CGraphDrawAppUi::HandleCommandL(TInt aCommand)
// ?implementation_description
// ----------------------------------------------------
//
void CGraphDrawAppUi::HandleCommandL(TInt aCommand)
    {
    switch ( aCommand )
        {
		case EAknSoftkeyExit:
        case EEikCmdExit:
            {
			// notify view2 to not validate/save the functions
			if (iTabGroup->ActiveTabIndex() == 1)
				iView2->iValidate = EFalse;
            Exit();
            break;
            }
		case EGraphDrawReturnToGraph:
            {
			// switch to 1st view
			iTabGroup->SetActiveTabByIndex( 0 );
            ActivateLocalViewL(TUid::Uid(iTabGroup->TabIdFromIndex(0)));
            break;
            }
		case EGraphDrawInsertData:
            {
			// switch to 2nd view
			iTabGroup->SetActiveTabByIndex( 1 );
            ActivateLocalViewL(TUid::Uid(iTabGroup->TabIdFromIndex(1)));
            break;
            }
        case EGraphDrawHelp:
            {
			// switch to 3rd view
			iTabGroup->SetActiveTabByIndex( 2 );
            ActivateLocalViewL(TUid::Uid(iTabGroup->TabIdFromIndex(2)));
            break;
            }
        default:
            break;      
        }
    }

// End of File  