/*
* ============================================================================
*  Name     : CGraphDrawApp from GraphDrawApp.cpp
*  Part of  : GraphDraw
*  Created  : 3/7/2003 by Makidis Michael
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Copyright: Makidis Michael 2003-2004
* ============================================================================
*/

// INCLUDE FILES
#include    "GraphDrawApp.h"
#include    "GraphDrawDocument.h"

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CGraphDrawApp::AppDllUid()
// Returns application UID
// ---------------------------------------------------------
//
TUid CGraphDrawApp::AppDllUid() const
    {
    return KUidGraphDraw;
    }

   
// ---------------------------------------------------------
// CGraphDrawApp::CreateDocumentL()
// Creates CGraphDrawDocument object
// ---------------------------------------------------------
//
CApaDocument* CGraphDrawApp::CreateDocumentL()
    {
    return CGraphDrawDocument::NewL( *this );
    }

// ================= OTHER EXPORTED FUNCTIONS ==============
//
// ---------------------------------------------------------
// NewApplication() 
// Constructs CGraphDrawApp
// Returns: created application object
// ---------------------------------------------------------
//
EXPORT_C CApaApplication* NewApplication()
    {
    return new CGraphDrawApp;
    }

// ---------------------------------------------------------
// E32Dll(TDllReason) 
// Entry point function for EPOC Apps
// Returns: KErrNone: No error
// ---------------------------------------------------------
//
GLDEF_C TInt E32Dll( TDllReason )
    {
    return KErrNone;
    }

// End of File  

