/*
* ============================================================================
*  Name     : CGraphDrawView3 from GraphDrawView3.h
*  Part of  : GraphDraw
*  Created  : 3/7/2003 by Makidis Michael
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Copyright: Makidis Michael 2003-2004
* ============================================================================
*/

// INCLUDE FILES
#include  "GraphDrawView3.h"
#include  "GraphDrawContainer3.h"
#include  "GraphDraw.hrh"
#include  <GraphDraw.rsg>
#include  <avkon.hrh>
#include  <aknviewappui.h>

// ================= MEMBER FUNCTIONS =======================

CGraphDrawView3::CGraphDrawView3(CGraphDrawDocument *aDocument)
:	iDocument(aDocument)
{

}

// ---------------------------------------------------------
// CGraphDrawView3::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
void CGraphDrawView3::ConstructL()
    {
    BaseConstructL( R_GRAPHDRAW_VIEW3 );
    }

// ---------------------------------------------------------
// CGraphDrawView3::~CGraphDrawView3()
// ?implementation_description
// ---------------------------------------------------------
//
CGraphDrawView3::~CGraphDrawView3()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
    }

// ---------------------------------------------------------
// TUid CGraphDrawView3::Id()
// ?implementation_description
// ---------------------------------------------------------
//
TUid CGraphDrawView3::Id() const
    {
    return KView3Id;
    }

// ---------------------------------------------------------
// CGraphDrawView3::HandleCommandL(TInt aCommand)
// ?implementation_description
// ---------------------------------------------------------
//
void CGraphDrawView3::HandleCommandL(TInt aCommand)
    {   
    switch ( aCommand )
        {
        case EAknSoftkeyOk:
            {
            iEikonEnv->InfoMsg( _L("view3 ok") );
            break;
            }
        case EAknSoftkeyBack:
            {
            AppUi()->HandleCommandL(EGraphDrawReturnToGraph);
            break;
            }
        default:
            {
            AppUi()->HandleCommandL( aCommand );
            break;
            }
        }
    }

// ---------------------------------------------------------
// CGraphDrawView3::HandleClientRectChange()
// ---------------------------------------------------------
//
void CGraphDrawView3::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CGraphDrawView3::DoActivateL(...)
// ?implementation_description
// ---------------------------------------------------------
//
void CGraphDrawView3::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CGraphDrawContainer3();
        iContainer->SetMopParent(this);
        iContainer->ConstructL( ClientRect() );
        AppUi()->AddToStackL( *this, iContainer );
        }
   }

// ---------------------------------------------------------
// CGraphDrawView3::HandleCommandL(TInt aCommand)
// ?implementation_description
// ---------------------------------------------------------
//
void CGraphDrawView3::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

// End of File

